mds_warehouse:
  target: dev
  outputs:
    dev:
      type: postgres
      threads: 4
      host: postgres_mds
      port: 5432
      user: airflow
      pass: airflow
      dbname: airflow
      schema: analytics
    ci:
      type: postgres
      host: postgres_mds
      user: airflow
      password: airflow
      port: 5432
      dbname: mds_warehouse
      schema: ci_testing
      threads: 4
